name: lint
on:
  push:
    branches:
      - master
      - develop
      - feature*
      - hotfix*
  pull_request:

jobs:
  check_format:
    runs-on: ubuntu-latest
    name: Check terraform file are formatted correctly
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1.31.1

  validate:
    runs-on: ubuntu-latest
    name: Validate terraform
    env:
      TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ secrets.TF_CLOUD_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: terraform validate
        uses: dflook/terraform-validate@v1.31.1

  tfsec:
    name: tfsec
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.2
        # with:
        #   soft_fail: true
